# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(450, 670)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(450, 670))
        MainWindow.setMaximumSize(QtCore.QSize(450, 670))
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(False)
        font.setWeight(50)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 260, 431, 111))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 6)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.circleButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.circleButton.setObjectName("circleButton")
        self.gridLayout.addWidget(self.circleButton, 0, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.triangleButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.triangleButton.setObjectName("triangleButton")
        self.gridLayout.addWidget(self.triangleButton, 0, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 0, 3, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 1, 3, 1, 1)
        self.squerButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.squerButton.setObjectName("squerButton")
        self.gridLayout.addWidget(self.squerButton, 0, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 1, 2, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 1, 0, 1, 1)
        self.inputBox = QtWidgets.QGroupBox(self.centralwidget)
        self.inputBox.setGeometry(QtCore.QRect(10, 380, 211, 281))
        self.inputBox.setObjectName("inputBox")
        self.outputBox = QtWidgets.QGroupBox(self.centralwidget)
        self.outputBox.setGeometry(QtCore.QRect(230, 380, 211, 281))
        self.outputBox.setObjectName("outputBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 431, 241))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.drawingLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.drawingLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.drawingLayout.setContentsMargins(0, 0, 0, 0)
        self.drawingLayout.setSpacing(6)
        self.drawingLayout.setObjectName("drawingLayout")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Geometry++"))
        self.circleButton.setText(_translate("MainWindow", "Круг"))
        self.pushButton_5.setText(_translate("MainWindow", "Б"))
        self.triangleButton.setText(_translate("MainWindow", "Треугольник"))
        self.pushButton_4.setText(_translate("MainWindow", "Прямоугольник"))
        self.pushButton_6.setText(_translate("MainWindow", "Трапеция"))
        self.squerButton.setText(_translate("MainWindow", "Квадрат"))
        self.pushButton_7.setText(_translate("MainWindow", "Ромб"))
        self.pushButton_8.setText(_translate("MainWindow", "А"))
        self.inputBox.setTitle(_translate("MainWindow", "Параметры"))
        self.outputBox.setTitle(_translate("MainWindow", "Результат"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
